/** @file
    @brief	ファイルマネージャ

    @date	2017.11.15
    @author	Takashi SHUDO
*/

#ifndef FILEMANAGER_H
#define FILEMANAGER_H

#include "sysconfig.h"

#ifdef GSC_FONTS_ENABLE_FONT_JISKAN24
#define DEFAULT_FONT	"jiskan24"
//#define INFO_AREA_HEIGHT	32
#define INFO_AREA_HEIGHT	34
#define SCRBAR_WIDTH		32
#define CONTROL_HEIGHT		64
#else
#ifndef GSC_FONTS_ENABLE_FONT_JISKAN16
#define DEFAULT_FONT	"8x16"
#else
#define DEFAULT_FONT	"jiskan16"
#endif
#define INFO_AREA_HEIGHT	24
#define SCRBAR_WIDTH		24
#define CONTROL_HEIGHT		48
#endif

#if GSC_GRAPHICS_DISPLAY_WIDTH >= 800
#define BUTTON_WIDTH	(48 * 2)
#define BUTTON_HEIGHT	48
#define BTN_INTERVAL	8
#else
#define BUTTON_WIDTH	(32 * 2)
#define BUTTON_HEIGHT	32
#define BTN_INTERVAL	8
#endif

#define FM_INFO_FORE_COLOR	RGB(200, 200, 200)
#define FM_INFO_BACK_COLOR	RGB(60, 60, 60)
#define FM_LIST_FORE_COLOR	RGB(150, 150, 150)
#define FM_LIST_BACK_COLOR	RGB(40, 40, 40)
#define FM_ACTIVE_FORE_COLOR	RGB(240, 240, 240)
#define FM_ACTIVE_BACK_COLOR	RGB(100, 100, 100)
#define FM_CTRL_FORE_COLOR	RGB(240, 240, 240)
#define FM_CTRL_BACK_COLOR	RGB(0, 0, 0)
#define MP_GREEN_COLOR		RGB(0, 250, 100)

#define CTRL_AREA_TOP	(GSC_GRAPHICS_DISPLAY_HEIGHT - CONTROL_HEIGHT)

#define V_BTN_LEFT	BTN_INTERVAL

#define H_BTN_TOP	(CTRL_AREA_TOP + (CONTROL_HEIGHT - BUTTON_HEIGHT)/2)

#define BTN_POS_X_DUP	BTN_INTERVAL
#define BTN_POS_Y_DUP	H_BTN_TOP

#define BTN_POS_X_DDOWN	(BTN_INTERVAL + BUTTON_WIDTH + BTN_INTERVAL)
#define BTN_POS_Y_DDOWN	H_BTN_TOP


#define VOL_DEF	30
#define VOL_MAX	99
#define VOL_MIN	0

#define VOL_HEIGHT	((CONTROL_HEIGHT*3)/4)
#define VOL_WIDTH	(VOL_MAX * 2)


//#define BTN_POS_X_STOP	(280 + BTN_INTERVAL + BUTTON_WIDTH)
#define BTN_POS_X_STOP	(GSC_GRAPHICS_DISPLAY_WIDTH - VOL_WIDTH - BTN_INTERVAL - BUTTON_WIDTH)
#define BTN_POS_Y_STOP	H_BTN_TOP

#define BTN_POS_X_PLAY	(280 + (BTN_INTERVAL + BUTTON_WIDTH) * 2)
#define BTN_POS_Y_PLAY	H_BTN_TOP

#define UO_ID_UP	1
#define UO_ID_DOWN	2
#define UO_ID_STOP	3
#define UO_ID_PLAY	4

#endif // FILEMANAGER_H
