/** @file
    @brief	音楽再生表示

    @date	2017.05.02
    @auther	Takashi SHUDO
*/

#ifndef MUSICPLAY_VIEW_H
#define MUSICPLAY_VIEW_H

#include "graphics.h"

#define MP_FORE_COLOR		RGB(150, 150, 200)
#define MP_BACK_COLOR		RGB(10, 10, 80)
#define MP_ACTIVE_FORE_COLOR	RGB(200, 200, 250)
#define MP_ACTIVE_BACK_COLOR	RGB(100, 100, 250)
#define MP_INACTIVE_FORE_COLOR	RGB(80, 80, 100)
#define MP_INACTIVE_BACK_COLOR	RGB(10, 10, 80)
#define MP_ACTIVE_BAR_COLOR	RGB(0, 150, 150)
#define MP_INACTIVE_BAR_COLOR	RGB(0, 50, 50)
#define MP_RED_COLOR		RGB(220, 50, 50)
#define MP_GREEN_COLOR		RGB(0, 250, 100)
#define MP_BLUE_COLOR		RGB(100, 100, 255)
#define MP_ORANGE_COLOR		RGB(250, 150, 50)

#if GSC_GRAPHICS_DISPLAY_WIDTH >= 800

#define TOPAREAMARGINE	8
#define BUTTON_WIDTH	96
#define BUTTONW_WIDTH	(96+48)
#define BUTTON_HEIGHT	96
#define BUTTONN_HEIGHT	60
#define V_BTN_LEFT	(GSC_GRAPHICS_DISPLAY_WIDTH - BUTTON_WIDTH - 1)
#define H_BTN_TOP	(GSC_GRAPHICS_DISPLAY_HEIGHT - BUTTON_WIDTH - 1)
#define BTN_INTERVAL	16
#define MPFONT	"jiskan24"
//#define MPFONT	"genshingothic_p18"
//#define MPFONT	"mplus_p2_p18"
#define TEXT_INTERVAL	32
#define SCRBAR_WIDTH	32
#define ARTWORK_LEFT	0
#define ARTWORK_TOP	204
#define INFO_WIDTH	(GSC_GRAPHICS_DISPLAY_WIDTH - 108 - SCRBAR_WIDTH)
#define INFO_HEIGHT	(GSC_GRAPHICS_DISPLAY_HEIGHT - 108 - SCRBAR_WIDTH - TEXT_INTERVAL - TOPAREAMARGINE - 8)
#define DEFFONT_WIDTH	12
#define DEFFONT_HEIGHR	24
#define LIST_ITEM_GAP	8

#define ICONGOBJ	(-8)
#define PLAYMODEBTN_WIDTH	64
#define PLAYMODEBTN_HEIGHT	48

#else // 480x272

#define TOPAREAMARGINE	4
#define BUTTON_WIDTH	64
#define BUTTONW_WIDTH	(64+32)
#define BUTTON_HEIGHT	64
#define BUTTONN_HEIGHT	40
#define V_BTN_LEFT	(GSC_GRAPHICS_DISPLAY_WIDTH - BUTTON_WIDTH)
#define H_BTN_TOP	(GSC_GRAPHICS_DISPLAY_HEIGHT - BUTTON_WIDTH)
#define BTN_INTERVAL	8
#define MPFONT	GSC_FONTS_DEFAULT_FONT
#define TEXT_INTERVAL	20
#define SCRBAR_WIDTH	16
#define ARTWORK_LEFT	0
#define ARTWORK_TOP	84
#define INFO_WIDTH	(GSC_GRAPHICS_DISPLAY_WIDTH - 80 - SCRBAR_WIDTH)
#define INFO_HEIGHT	(GSC_GRAPHICS_DISPLAY_HEIGHT - 80 - SCRBAR_WIDTH - TEXT_INTERVAL - TOPAREAMARGINE + 8)
#define DEFFONT_WIDTH	8
#define DEFFONT_HEIGHR	16
#define LIST_ITEM_GAP	6

#define ICONGOBJ	0
#define PLAYMODEBTN_WIDTH	48
#define PLAYMODEBTN_HEIGHT	32
#endif

#define GOBJ_WIDTH	BUTTON_WIDTH
#define GOBJ_WWIDTH	BUTTONW_WIDTH
#define GOBJ_HEIGHT	BUTTON_HEIGHT

#define GR	32
#define GRW	48
#define GX(x)	(GOBJ_WIDTH/GR*x)
#define GXW(x)	(GOBJ_WWIDTH/GRW*x)
#define GY(y)	(GOBJ_HEIGHT/GR*y)

extern const struct st_rect info_rect;

extern const unsigned int active_color;
extern const unsigned int fore_color;
extern const unsigned int back_color;
extern const unsigned int green_color;

#endif // MUSICPLAY_VIEW_H
